src/accounts/urls.py
from django.conf.urls import url

from .views import login_page, register_page


urlpatterns = [
    url(r'^login/$', login_page, name="login"),
    url(r'^register/$', register_page, name="register")
]

src/carts/urls.py
from django.conf.urls import url

from carts.views import cart_home, cart_update, cart_checkout


urlpatterns = [
    url(r'^$', cart_home, name="home"),
    url(r'^update/$', cart_update, name="update"),
    url(r'^checkout/$', cart_checkout, name="checkout")
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from .views import home_page, contact_page

from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name="home"),
    url(r'^contact/$', contact_page, name="contact"),
    url(r'^accounts/', include("accounts.urls", namespace="account")),
    url(r'^logout', LogoutView.as_view(), name="logout"),
    url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^bootstrap/$', TemplateView.as_view(template_name="bootstrap/example.html")),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^search/', include("search.urls", namespace="search"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,
                                       document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from products.views import (ProductListView,
                            ProductDetailView
                            )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name="list"),
    url(r'^product/(?P<slug>[\w-]+)/$', ProductDetailView.as_view(),
        name="details")
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<script src="https://kit.fontawesome.com/611a13a2eb.js" crossorigin="anonymous"></script>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

src/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/templates/base/nav.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'account:login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'account:register' as register_url %}
{% url 'products:list' as products_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">{% if brand_name %}{{brand_name}}{% else %}{{_("Navbar")}}{% endif %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
              <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
              <a class="nav-link" href="{{ contact_url }}">contact</a>
            </li>
            <li class="nav-item {% if request.path == products_url %}active{% endif %}">
                    <a class="nav-link" href="{{ products_url }}">Products</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link" href="{{ logout_url }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                <a class="nav-link" href="{{ cart_url }}">{{request.session.cart_items}}<i class="fas fa-shopping-cart"></i></a>
            </li>
          </ul>
          {%include 'search/snippets/search-form.html'%}
        </div>
      </nav>