src/carts/urls.py
from django.conf.urls import url

from carts.views import cart_home, cart_update, cart_checkout


urlpatterns = [
    url(r'^$', cart_home, name="home"),
    url(r'^update/$', cart_update, name="update"),
    url(r'^checkout/$', cart_checkout, name="checkout")
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from .views import home_page, contact_page

from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name="home"),
    url(r'^contact/$', contact_page, name="contact"),
    url(r'^accounts/', include("accounts.urls", namespace="account")),
    url(r'^logout', LogoutView.as_view(), name="logout"),
    url(r'^cart/', include("carts.urls", namespace="cart")),
    url(r'^bootstrap/$', TemplateView.as_view(template_name="bootstrap/example.html")),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^search/', include("search.urls", namespace="search"))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,
                                       document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)

src/carts/models.py
from decimal import Decimal
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.conf import settings
from products.models import Product


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def get_or_new(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)

        if qs.count() == 1:
            cart = qs.first()
            new_obj = False
            if cart.user is None and request.user.is_authenticated():
                cart.user = request.user
                cart.save()
        else:
            new_obj = True
            cart = self.new(request.user)
        request.session["cart_id"] = cart.id

        return cart, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(max_digits=30, decimal_places=2, default=0.00)
    sub_total = models.DecimalField(max_digits=30,
                                    decimal_places=2,
                                    default=0.00)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

    @property
    def subtotal(self):
        return self.sub_total


def m2m_change_cart_recever(sender, instance, action, *args, **kwargs):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        products = instance.products.all()
        total = 0

        for product in products:
            total += product.price

        if instance.sub_total != total:
            instance.sub_total = total
            instance.save()


m2m_changed.connect(m2m_change_cart_recever, sender=Cart.products.through)


def pre_save_cart_recever(sender, instance, *args, **kwargs):
    if instance.sub_total > 0:
        instance.total = Decimal( instance.sub_total) * Decimal(1.08)  # 8% tax
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_recever, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect
from .models import Cart
from products.models import Product
from orders.models import Order


def cart_home(request):
    cart, check = Cart.objects.get_or_new(request)
    return render(request, 'cart/view.html', {"cart": cart})


def cart_update(request):
    if request.method == "POST":
        product_id = request.POST["product"]
        if product_id is not None:
            try:
                product = Product.objects.get(id=product_id)
            except Product.DoesNotExist:
                print("message user that it gone")
                redirect("cart:home")

            cart, is_new = Cart.objects.get_or_new(request)
            if product in cart.products.all():
                cart.products.remove(product)
            else:
                cart.products.add(product)

        request.session["cart_items"] = cart.products.count()
    return redirect("cart:home")


def cart_checkout(request):
    cart, is_new_cart = Cart.objects.get_or_new(request)

    if is_new_cart:
        return redirect("cart:home")
    else:
        order, is_new_order = Order.objects.get_or_new(cart=cart)
    return render(request, "cart/checkout.html", {"order": order})

src/carts/templates/cart/checkout.html
{% extends 'base.html' %}

{% block content %}
<div class=container>
    <h3>Total Item: {{ order.cart.products.count }}</h3>
    <h3>Cart Total: {{ order.cart.total }}</h3>
    <h3>Shipping Total: {{ order.shipping_total }}</h3>
    <h3>Order Total: {{ order.total }}</h3>
</div>
{% endblock %}

src/carts/templates/cart/view.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h3>Cart</h3>
    <div class="row">
        <div class="col-12">
            {% if cart.products.exists %}
            <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Product Price</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for product in cart.products.all %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>
                            <a class="text-info" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            <br>
                            {% include 'product/snippets/product-update.html' with produt=product cart=cart in_cart=True %}
                        </td>
                        <td>{{ product.price }}</td>
                      </tr>
                    {% endfor %}
                      <tr class="bg-info">
                        <td colspan="2">Sub Total:</td>
                        <td>{{ cart.subtotal }}</td>
                      </tr>
                      <tr class="bg-warning">
                        <td colspan="2">Total:</td>
                        <td>{{ cart.total }}</td>
                      </tr>
                      <tr>
                        <td colspan="2"></td>
                          <td><a href="{% url 'cart:checkout' %}" class="btn btn-success btn-lg">Checkout</a></td>
                        </tr>
                    </tbody>
                  </table
                  {% else %}
                  <p class="lead">
                      No Item in the cart
                  </p>
                  {% endif %}
        </div>
    </div>
</div>
{% endblock %}